### PR TITLE
Robot animations on board + major hex grid refactor/redesign

### PR DESCRIPTION
**Pull request by AlexNisnevich**
#302.

- [x] Move animations
- [x] Attack animations

### CODE REVIEW

**Comment by Dbz** [comment]
Let me know when we can put this on staging for me to test out :)

**Comment by Dbz** [comment]
Move animations and attack animations are VERY HELPFUL to indicate what is going on in your opponent's turn. If a robot attacks and dies, then it doesn't do the attack animation.

**Comment by AlexNisnevich** [comment]
@Dbz Good point – try it now!

**Comment by Dbz** [comment]
This is way better!

**Pull request merged**
