### PR TITLE
Event play animations

### PR DESCRIPTION
**Pull request by AlexNisnevich**

### CODE REVIEW

**Comment by AlexNisnevich** [comment]
A few bugs:
- If you play the same event card multiple times, it'll only appear the first time.
- The cards always appear from the bottom, even if your opponent plays it.

**Comment by AlexNisnevich** [comment]
@Dbz Could you take a look at how event animations work? I'm putting it up on staging, should be up in 5-10 min.

**Comment by Dbz** [comment]
This is infinitely better. I think it could still be improved if there was some sort of wave effect/lighting effect or something else when you play the card. However, this is a great start by displaying the event that got played. It also might help to slightly flash the card in the history so people can highlight the history and read the card if they couldn't read the text quickly enough.

**Comment by AlexNisnevich** [comment]
@Dbz Hmm, could you make separate issues for the points that you've mentioned? I agree with them, but they can be done in separate PRs. I'll merge this as-is for now. 

Also, what do you think about animations for playing robot/structure cards? Probably not necessary, since there's a physical object that appears on the board, right?

**Comment by Dbz** [comment]
I think for now it might not be necessary, but eventually you want animations for all cards played. It's just a question of what those animations are like. And it might be great to get a really good animator on board with the project who can do some cool stuff. Like in HS there are standard animations for playing cards, and then also special animations for legendaries.

**Pull request merged**
