### PR TITLE
Practice mode against AI

### PR DESCRIPTION
**Pull request by AlexNisnevich**
#348, #350.

### CODE REVIEW

**Comment by Dbz** [comment]
Very interesting. I will test this :)

**Comment by Dbz** [comment]
Nice, I think it would be better if enemy robots try to attack the kernel more often.

**Comment by Dbz** [comment]
Also, how do you feel about defenders being allowed to attack kernels?

**Comment by AlexNisnevich** [comment]
Defenders should not be allowed to attack kernels. That said, maybe the AI should have less defenders in its deck since it can't use them effectively?

**Comment by AlexNisnevich** [comment]
As it stands, the AI attacks the kernel each turn when a robot is in range of the kernel.

**Comment by Dbz** [comment]
Yeah, I wouldn't put defenders in the AI deck. I also felt sometimes robots would meander about before attacking the kernel or trying to occupy all of the spawn spots for an auto-win.

**Comment by AlexNisnevich** [comment]
Try it now, @Dbz !

**Comment by Dbz** [comment]
```
Game]: Computer played Earthquake. Dojo Disciple was destroyed. Blue Bot was destroyed. Two Bot was destroyed. Two Bot was destroyed. Blue Bot was destroyed.
```

The computer played an Earthquake and killed all of it's own robots without really damaging me.

**Comment by AlexNisnevich** [comment]
Hah, that'll happen. The computer plays cards essentially randomly.

**Comment by AlexNisnevich** [comment]
I could in theory do some kind of min-max, but the game tree is really large (at any given point there could be hundreds of possible moves), so I'm a bit hesitant to bring heavy machinery like that in.

**Comment by AlexNisnevich** [comment]
I could also take out Earthquake from the AI deck for now, but I don't mind it occasionally making silly mistakes :-)

**Comment by jacobnisnevich** [comment]
If its gonna be a legit AI then we probably should do a min-max tree, but I think it's meant to be just a mode to test out your creations right?

**Comment by AlexNisnevich** [comment]
Yeah. We can always work on making the AI smarter (maybe even have difficulty levels in the future), but that's not the highest priority for now with this PR, like @jacobnisnevich said.

**Comment by Dbz** [comment]
Yep yep. I was thinking just take it out.

**Comment by Dbz** [comment]
Cool, I'll give this another whirl and consider it before approving :)

**Comment by AlexNisnevich** [comment]
I'll just merge it into master now so that I can put up the animations branch on staging.

**Comment by Dbz** [comment]
👍

**Comment by Dbz** [comment]
If I can think of anything else I'll just make a new issue.

**Pull request merged**
